#!/usr/bin/env python

# Copyright (c) 2019 Computer Vision Center (CVC) at the Universitat Autonoma de
# Barcelona (UAB).
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.

import glob
import os
import sys

try:
    #sys.path.append(glob.glob('../carla/dist/carla-*%d.%d-%s.egg' % (
    sys.path.append(glob.glob('/home/alexandracarlson/Desktop/carla/PythonAPI/carla/dist/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

import carla

import random
import time


def main():
    actor_list = []

    # In this tutorial script, we are going to add a vehicle to the simulation
    # and let it drive in autopilot. We will also create a camera attached to
    # that vehicle, and save all the images generated by the camera to disk.

    try:
        print('trying')
        # First of all, we need to create the client that will send the requests
        # to the simulator. Here we'll assume the simulator is accepting
        # requests in the localhost at port 2000.
        client = carla.Client('localhost', 2000)
        client.set_timeout(2.0)
        print('localhost')

        # Once we have a client we can retrieve the world that is currently
        # running.
        world = client.get_world()
        print('client world')
        # The world contains the list blueprints that we can use for adding new
        # actors into the simulation.
        blueprint_library = world.get_blueprint_library()

        # Now let's filter all the blueprints of type 'vehicle' and choose one
        # at random.
        bp = random.choice(blueprint_library.filter('vehicle'))

        # A blueprint contains the list of attributes that define a vehicle's
        # instance, we can read them and modify some of them. For instance,
        # let's randomize its color.
        if bp.has_attribute('color'):
            color = random.choice(bp.get_attribute('color').recommended_values)
            bp.set_attribute('color', color)

        # Now we need to give an initial transform to the vehicle. We choose a
        # random transform from the list of recommended spawn points of the map.
        transform = random.choice(world.get_map().get_spawn_points())

        # So let's tell the world to spawn the vehicle.
        vehicle = world.spawn_actor(bp, transform)
        print('got vehicle')
        # It is important to note that the actors we create won't be destroyed
        # unless we call their "destroy" function. If we fail to call "destroy"
        # they will stay in the simulation even after we quit the Python script.
        # For that reason, we are storing all the actors we create so we can
        # destroy them afterwards.
        actor_list.append(vehicle)
        print('created %s' % vehicle.type_id)

        # Let's put the vehicle to drive around.
        vehicle.set_autopilot(True)

        # Let's add now a "depth" camera attached to the vehicle. Note that the
        # transform we give here is now relative to the vehicle.
        camera_bp = blueprint_library.find('sensor.camera.depth')
        camera_transform = carla.Transform(carla.Location(x=1.5, z=2.4))
        camera = world.spawn_actor(camera_bp, camera_transform, attach_to=vehicle)
        actor_list.append(camera)
        print('created %s' % camera.type_id)

        # Now we register the function that will be called each time the sensor
        # receives an image. In this example we are saving the image to disk
        # converting the pixels to gray-scale.
        cc = carla.ColorConverter.LogarithmicDepth
        camera.listen(lambda image: image.save_to_disk('carla_out/%06d_depth.png' % image.frame, cc))

        ## add normal map camera
        normalcam_bp = blueprint_library.find('sensor.camera.normal_map')
        normalcam = world.spawn_actor(normalcam_bp, camera_transform , attach_to=vehicle)
        actor_list.append(normalcam)
        print('created %s'%normalcam.type_id)
        normalcam.listen(lambda image: image.save_to_disk('carla_out/%06d_normal.png' % image.frame))

        ## add basecolor map camera
        bccam_bp = blueprint_library.find('sensor.camera.mat_map')
        bccam = world.spawn_actor(bccam_bp, camera_transform , attach_to=vehicle)
        actor_list.append(bccam)
        print('created %s'%bccam.type_id)
        bccam.listen(lambda image: image.save_to_disk('carla_out/%06d_basecolorfromlighting.png' % image.frame))

        ## add specular map camera
        speccam_bp = blueprint_library.find('sensor.camera.specular')
        speccam = world.spawn_actor(speccam_bp, camera_transform , attach_to=vehicle)
        actor_list.append(speccam)
        print('created %s'%speccam.type_id)
        speccam.listen(lambda image: image.save_to_disk('carla_out/%06d_specularfromlighting.png' % image.frame))

        ## add roughness map camera
        roughcam_bp = blueprint_library.find('sensor.camera.roughness')
        roughcam = world.spawn_actor(roughcam_bp, camera_transform , attach_to=vehicle)
        actor_list.append(roughcam)
        print('created %s'%roughcam.type_id)
        roughcam.listen(lambda image: image.save_to_disk('carla_out/%06d_roughness.png' % image.frame))

        ## add metallic map camera
        metcam_bp = blueprint_library.find('sensor.camera.metallic')
        metcam = world.spawn_actor(metcam_bp, camera_transform , attach_to=vehicle)
        actor_list.append(metcam)
        print('created %s'%metcam.type_id)
        metcam.listen(lambda image: image.save_to_disk('carla_out/%06d_metallix.png' % image.frame))

        ## add semantic segmentation camera
        semsegcam_bp = blueprint_library.find('sensor.camera.semantic_segmentation')
        semsegcam = world.spawn_actor(semsegcam_bp, camera_transform , attach_to=vehicle)
        actor_list.append(semsegcam)
        print('created %s'%semsegcam.type_id)
        semsegcam.listen(lambda image: image.save_to_disk('carla_out/%06d_semseg.png' % image.frame))

        # Oh wait, I don't like the location we gave to the vehicle, I'm going
        # to move it a bit forward.
        location = vehicle.get_location()
        location.x += 40
        vehicle.set_location(location)
        print('moved vehicle to %s' % location)

        # But the city now is probably quite empty, let's add a few more
        # vehicles.
        transform.location += carla.Location(x=40, y=-3.2)
        transform.rotation.yaw = -180.0
        for _ in range(0, 10):
            transform.location.x += 8.0

            bp = random.choice(blueprint_library.filter('vehicle'))

            # This time we are using try_spawn_actor. If the spot is already
            # occupied by another object, the function will return None.
            npc = world.try_spawn_actor(bp, transform)
            if npc is not None:
                actor_list.append(npc)
                npc.set_autopilot(True)
                print('created %s' % npc.type_id)

        time.sleep(15)

    finally:

        print('destroying actors')
        camera.destroy()
        normalcam.destroy()
        semsegcam.destroy()
        client.apply_batch([carla.command.DestroyActor(x) for x in actor_list])
        print('done.')


if __name__ == '__main__':

    main()
